version: 0.1
phases:
  install:
    commands:
      - chmod +x /usr/bin/nohup
      - chmod +x /usr/bin/dockerd
      - /usr/bin/nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI-fpm
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $(echo $COMMIT_HASH)
      - echo `image tag:` $(echo $IMAGE_TAG) 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ./site && composer install --no-dev && composer update --no-dev 
      - docker build -t $REPOSITORY_URI-fpm:latest -f ./fpm.Dockerfile .
      - docker build -t $REPOSITORY_URI-nginx:latest -f ./nginx.Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI-fpm:latest
      - docker push $REPOSITORY_URI-nginx:latest
artifacts:
  files: 
